@startuml

title __APP's Class Diagram__\n

  namespace com.example.projet_final {
    class com.example.projet_final.BuildConfig {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.MainActivity {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.MapsActivity {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.MarkerManager {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.Notification {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.Profile {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.User {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.UserService {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.WorkerService {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.app {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.marker {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.multi_activity {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.notif_click {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.popup {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.resulttReq {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.saveLocation {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.sign_up {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.tasks {
    }
  }
  

  namespace com.example.projet_final {
    class com.example.projet_final.update_profile {
    }
  }
  

  com.example.projet_final.MainActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.MapsActivity .up.|> com.google.android.gms.maps.GoogleMap.OnMarkerClickListener
  com.example.projet_final.MapsActivity .up.|> com.google.android.gms.maps.OnMapReadyCallback
  com.example.projet_final.MapsActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.MapsActivity o-- com.example.projet_final.User : corentUser
  com.example.projet_final.MapsActivity o-- com.example.projet_final.User : user
  com.example.projet_final.MarkerManager -up-|> com.google.maps.android.clustering.view.DefaultClusterRenderer
  com.example.projet_final.Profile -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.Profile o-- com.example.projet_final.User : user
  com.example.projet_final.UserService -up-|> android.app.Service
  com.example.projet_final.UserService o-- com.example.projet_final.User : user
  com.example.projet_final.WorkerService -up-|> android.app.Service
  com.example.projet_final.WorkerService o-- com.example.projet_final.User : user
  com.example.projet_final.app -up-|> android.app.Application
  com.example.projet_final.marker .up.|> com.google.maps.android.clustering.ClusterItem
  com.example.projet_final.multi_activity -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.notif_click -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.notif_click o-- com.example.projet_final.User : user
  com.example.projet_final.popup -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.saveLocation -up-|> android.app.Service
  com.example.projet_final.sign_up -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.tasks -up-|> androidx.appcompat.app.AppCompatActivity
  com.example.projet_final.tasks o-- com.example.projet_final.Notification : notification
  com.example.projet_final.update_profile -up-|> androidx.appcompat.app.AppCompatActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
